apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu
  namespace: inference
spec:
  hard:
    requests.nvidia.com/gpu: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu
  namespace: bench
spec:
  hard:
    requests.nvidia.com/gpu: "4"
