apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: {{ .Values.versions.certManager | quote }}
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/platform/cert-manager/values.yaml
    - repoURL: {{ .Values.repo.url | quote }}
      targetRevision: {{ .Values.repo.revision | quote }}
      ref: values
  destination:
    server: {{ .Values.destinationServer }}
    namespace: cert-manager
  syncPolicy:
    {{- include "apps.syncPolicy" . | nindent 4 }}
