apiVersion: v1
kind: Secret
metadata:
  name: kserve-charts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: kserve-charts
  type: helm
  url: ghcr.io/kserve/charts
  enableOCI: "true"
