apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccountName }}
  {{- if .Values.frontend.gsaEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.frontend.gsaEmail | quote }}
  {{- end }}
